# Custom Language File for Launcher Customizer

[ejs.app]
title = "Cursed Lands Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/FRErlingx/CLL"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/YwhNEVQdae"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/FRErlingx/CLL/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR CURSED LAND'S"
welcomeDescription = "ODans un monde où le surnaturel est présent quatre hommes sont à la tête de tout ça... les Monarques. Découvrez un monde imaginer de toutes pièces par nos équipes et créer votre propres histoires."
welcomeDescCTA = "Vous etes a deux pas des terres de Cursed Land's"
